- name: install required packages
  yum:
    name:
      - tftp-server
    state: present
  become: yes


- name: Create TFTP Directory
  file:
    path: "{{ TFTP_DIR }}"
    state: directory
    owner: root
    group: root
  become: yes

- name: Creating Grub Config
  template:
    src: grub.cfg.j2
    dest: "{{ TFTP_DIR }}/grub.cfg"
  become: yes

- name: Configure TFTP service
  template:
    src:  tftp.service.j2
    dest: /usr/lib/systemd/system/tftp.service
  become: yes

- name: Start TFTP Server
  service:
    name: tftp
    daemon_reload: yes
    state: started
    enabled: yes
  become: yes